const moviesData = {
  n: 40,
  images_url: "https://image.tmdb.org/t/p/w500",
  genres: [
    {
      id: 28,
      name: "Acción",
    },
    {
      id: 12,
      name: "Aventura",
    },
    {
      id: 16,
      name: "Animación",
    },
    {
      id: 35,
      name: "Comedia",
    },
    {
      id: 80,
      name: "Crimen",
    },
    {
      id: 99,
      name: "Documental",
    },
    {
      id: 18,
      name: "Drama",
    },
    {
      id: 10751,
      name: "Familia",
    },
    {
      id: 14,
      name: "Fantasía",
    },
    {
      id: 36,
      name: "Historia",
    },
    {
      id: 27,
      name: "Terror",
    },
    {
      id: 10402,
      name: "Música",
    },
    {
      id: 9648,
      name: "Misterio",
    },
    {
      id: 10749,
      name: "Romance",
    },
    {
      id: 878,
      name: "Ciencia ficción",
    },
    {
      id: 10770,
      name: "Película de TV",
    },
    {
      id: 53,
      name: "Suspense",
    },
    {
      id: 10752,
      name: "Bélica",
    },
    {
      id: 37,
      name: "Western",
    },
  ],
  results: [
    {
      popularity: 42.854,
      vote_count: 20381,
      video: false,
      poster_path: "/1yWmCAIGSVNuTOGyz9F48W9g1Ux.jpg",
      id: 550,
      adult: false,
      backdrop_path: "/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg",
      original_language: "en",
      original_title: "Fight Club",
      genre_ids: [18],
      title: "El club de la lucha",
      vote_average: 8.4,
      overview:
        "Un joven sin ilusiones lucha contra su insomnio, consecuencia quizás de su hastío por su gris y rutinaria vida. En un viaje en avión conoce a Tyler Durden, un carismático vendedor de jabón que sostiene una filosofía muy particular: el perfeccionismo es cosa de gentes débiles; en cambio, la autodestrucción es lo único que hace que realmente la vida merezca la pena. Ambos deciden entonces formar un club secreto de lucha donde descargar sus frustaciones y su ira que tendrá un éxito arrollador.",
      release_date: "1999-10-15",
    },
    {
      popularity: 57.28,
      vote_count: 17472,
      video: false,
      poster_path: "/dc1fX265fZIIY5Hab8I7CdETyJy.jpg",
      id: 278,
      adult: false,
      backdrop_path: "/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg",
      original_language: "en",
      original_title: "The Shawshank Redemption",
      genre_ids: [18, 80],
      title: "Cadena perpetua",
      vote_average: 8.7,
      overview:
        "Acusado del asesinato de su mujer, Andrew Dufresne, tras ser condenado a cadena perpetua, es enviado a la prisión de Shawshank. Con el paso de los años conseguirá ganarse la confianza del director del centro y el respeto de sus compañeros presidiarios, especialmente de Red, el jefe de la mafia de los sobornos.",
      release_date: "1994-09-23",
    },
    {
      popularity: 46.579,
      vote_count: 19839,
      video: false,
      poster_path: "/hNcQAuquJxTxl2fJFs1R42DrWcf.jpg",
      id: 680,
      adult: false,
      backdrop_path: "/w7RDIgQM6bLT7JXtH4iUQd3Iwxm.jpg",
      original_language: "en",
      original_title: "Pulp Fiction",
      genre_ids: [53, 80],
      title: "Pulp Fiction",
      vote_average: 8.5,
      overview:
        "Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.",
      release_date: "1994-09-10",
    },
    {
      popularity: 60.784,
      id: 122,
      video: false,
      vote_count: 16498,
      vote_average: 8.5,
      title: "El señor de los anillos: el retorno del rey",
      release_date: "2003-12-01",
      original_language: "en",
      original_title: "The Lord of the Rings: The Return of the King",
      genre_ids: [12, 14, 28],
      backdrop_path: "/9DeGfFIqjph5CBFVQrD6wv9S7rR.jpg",
      adult: false,
      overview:
        "Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de que se decida el destino de la Tierra Media, y por primera vez en mucho tiempo, parece que hay una pequeña esperanza. La atención del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, y del cual Aragorn tendrá que reclamar el trono para ocupar su puesto de rey. Pero las fuerzas de Sauron ya se preparan para lanzar el último y definitivo ataque contra el reino de Gondor, la batalla que decidirá el destino de todos. Mientras tanto, Frodo y Sam continuan su camino hacia Mordor, a la espera de que Sauron no repare en que dos pequeños Hobbits se acercan cada día más al final de su camino, el Monte del Destino.",
      poster_path: "/mWuFbQrXyLk2kMBKF9TUPtDwuPx.jpg",
    },
    {
      popularity: 42.03,
      vote_count: 19182,
      video: false,
      poster_path: "/azV6hV99lYkdhydsQbJCI6FqMl4.jpg",
      id: 13,
      adult: false,
      backdrop_path: "/7c9UVPPiTPltouxRVY6N9uugaVA.jpg",
      original_language: "en",
      original_title: "Forrest Gump",
      genre_ids: [35, 18, 10749],
      title: "Forrest Gump",
      vote_average: 8.5,
      overview:
        "Forrest Gump es un chico con deficiencias mentales no muy profundas y con alguna incapacidad motora que, a pesar de todo, llegará a convertirse, entre otras cosas, en un héroe durante la Guerra del Vietnam. Su persistencia y bondad le llevarán a conseguir una gran fortuna, ser objeto del clamor popular y a codearse con las más altas esferas sociales y políticas del país. Siempre sin olvidar a Jenny, su gran amor desde que era niño.",
      release_date: "1994-07-06",
    },
    {
      popularity: 73.57,
      vote_count: 23630,
      video: false,
      poster_path: "/8QDQExnfNFOtabLDKqfDQuHDsIg.jpg",
      id: 155,
      adult: false,
      backdrop_path: "/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
      original_language: "en",
      original_title: "The Dark Knight",
      genre_ids: [18, 28, 80, 53],
      title: "El caballero oscuro",
      vote_average: 8.5,
      overview:
        "Batman/Bruce Wayne regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman se propone destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra su eficacia, pero, de repente, aparece Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.",
      release_date: "2008-07-16",
    },
    {
      popularity: 39.145,
      id: 429,
      video: false,
      vote_count: 5443,
      vote_average: 8.4,
      title: "El bueno, el feo y el malo",
      release_date: "1966-12-23",
      original_language: "it",
      original_title: "Il buono, il brutto, il cattivo",
      genre_ids: [37],
      backdrop_path: "/x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
      adult: false,
      overview:
        "Durante la Guerra de Secesión, tres cazadores de recompensas se lanzan a la búsqueda de un tesoro que ninguno de los tres truhanes puede localizar sin la ayuda de los otros dos. Tuco sabe que el tesoro se encuentra en un cementerio, mientras que Joe conoce el nombre inscrito en la tumba que lo esconde. Mientras tanto, Sentenza no duda en matar a mujeres y niños para conseguir su meta. De esta forma, los tres hombres colaboran en apariencia, pero al final intentarán eliminarse mutuamente.",
      poster_path: "/fSWnIXsxA47smMLwRELSWkxbVJ.jpg",
    },
    {
      popularity: 48.154,
      vote_count: 13224,
      video: false,
      poster_path: "/wLXd1Cd0XW7DhXayfC0Ok5ago9r.jpg",
      id: 238,
      adult: false,
      backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
      original_language: "en",
      original_title: "The Godfather",
      genre_ids: [18, 80],
      title: "El padrino",
      vote_average: 8.7,
      overview:
        'Don Vito Corleone, conocido dentro de los círculos del hampa como "El Padrino", es el patriarca de una de las cinco familias que ejercen el mando de la Cosa Nostra en Nueva York en los años 40. Don Corleone tiene cuatro hijos; una chica, Connie, y tres varones, Sonny, Michael y Freddie, al que envían exiliado a Las Vegas, dada su incapacidad para asumir puestos de mando en la "Familia". Cuando el Padrino reclina intervenir en el negocio de estupefacientes, empieza una cruenta lucha de violentos episodios entre las distintas familias del crimen organizado.',
      release_date: "1972-03-14",
    },
    {
      popularity: 31.382,
      id: 424,
      video: false,
      vote_count: 10522,
      vote_average: 8.6,
      title: "La lista de Schindler",
      release_date: "1993-11-30",
      original_language: "en",
      original_title: "Schindler's List",
      genre_ids: [18, 36, 10752],
      backdrop_path: "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
      adult: false,
      overview:
        "Oskar Schindler, un hombre de enorme astucia y talento para las relaciones públicas, organiza un ambicioso plan para ganarse la simpatía de los nazis. Después de la invasión de Polonia por los alemanes, consigue, gracias a sus relaciones con los nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente. Su gerente, también judío, es el verdadero director en la sombra, pues Schindler no tiene el menor conocimiento industrial.",
      poster_path: "/3Ho0pXsnMxpGJWqdOi0KDNdaTkT.jpg",
    },
    {
      popularity: 38.426,
      vote_count: 7845,
      video: false,
      poster_path: "/iJqEycKV96JCBWqx2Ij38Ufa8EH.jpg",
      id: 240,
      adult: false,
      backdrop_path: "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
      original_language: "en",
      original_title: "The Godfather: Part II",
      genre_ids: [18, 80],
      title: "El padrino: parte II",
      vote_average: 8.6,
      overview:
        "Continuación de la saga de los Corleone con dos historias paralelas: la elección de Michael Corleone como jefe de los negocios familiares y los orígenes del patriarca, el ya fallecido Don Vito, primero en Sicilia y luego en Estados Unidos, donde, empezando desde abajo, llegó a ser un poderosísimo jefe de la mafia de Nueva York.",
      release_date: "1974-12-20",
    },
    {
      popularity: 33.94,
      id: 89,
      video: false,
      vote_count: 6818,
      vote_average: 7.8,
      title: "Indiana Jones y la última cruzada",
      release_date: "1989-05-24",
      original_language: "en",
      original_title: "Indiana Jones and the Last Crusade",
      genre_ids: [12, 28],
      backdrop_path: "/diTtDL61hIwozEGBwEsw7uA7qN9.jpg",
      adult: false,
      overview:
        "En esta tercera entrega, el padre del protagonista (Harrison Ford), Henry Jones, también arqueólogo (Sean Connery), es secuestrado cuando buscaba el Santo Grial. Indiana tendrá que ir a rescatarlo y, de paso, intentar hacerse con la preciada reliquia, que también ambicionan los nazis.",
      poster_path: "/rOx2Yy8ffxkOzZbckPBOWjXF0TX.jpg",
    },
    {
      popularity: 57.203,
      vote_count: 10361,
      video: false,
      poster_path: "/vlsi5iZcfDChKNGNvRp7Zp3SULH.jpg",
      id: 129,
      adult: false,
      backdrop_path: "/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg",
      original_language: "ja",
      original_title: "千と千尋の神隠し",
      genre_ids: [16, 10751, 14],
      title: "El viaje de Chihiro",
      vote_average: 8.5,
      overview:
        "Chihiro es una niña de diez años que está mudándose con sus padres a un nuevo hogar. Por el camino, la familia se topa con un enorme edificio rojo en cuyo centro se abre un largo túnel. Al otro lado del pasadizo se dibuja una ciudad fantasma. En el restaurante abandonado de esta ciudad, los padres de Chihiro encuentran una gran variedad de platos deliciosos y deciden quedarse a comer, pero, al probar bocado, se transforman en cerdos. Presa del pánico, Chihiro huye y empieza a desmaterializarse poco a poco. El enigmático Haku le explicará el funcionamiento del universo en el que ha caído. Para salvar a sus padres, la niña tendrá que enfrentarse a la terrible Yubaba, que tiene el aspecto de una arpía diabólica.",
      release_date: "2001-07-20",
    },
    {
      popularity: 66.189,
      id: 120,
      video: false,
      vote_count: 17961,
      vote_average: 8.3,
      title: "El señor de los anillos: la comunidad del anillo",
      release_date: "2001-12-18",
      original_language: "en",
      original_title: "The Lord of the Rings: The Fellowship of the Ring",
      genre_ids: [12, 14, 28],
      backdrop_path: "/vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg",
      adult: false,
      overview:
        "En la Tierra Media, el Señor Oscuro Saurón creó los Grandes Anillos de Poder, forjados por los herreros Elfos. Tres para los reyes Elfos, siete para los Señores Enanos, y nueve para los Hombres Mortales. Secretamente, Saurón también forjó un anillo maestro, el Anillo Único, que contiene en sí el poder para esclavizar a toda la Tierra Media. Con la ayuda de un grupo de amigos y de valientes aliados, Frodo emprende un peligroso viaje con la misión de destruir el Anillo Único. Pero el Señor Oscuro Sauron, quien creara el Anillo, envía a sus servidores para perseguir al grupo. Si Sauron lograra recuperar el Anillo, sería el final de la Tierra Media.",
      poster_path: "/9xtH1RmAzQ0rrMBNUMXstb2s3er.jpg",
    },
    {
      popularity: 54.469,
      vote_count: 27539,
      video: false,
      poster_path: "/tXQvtRWfkUUnWJAn2tN3jERIUG.jpg",
      id: 27205,
      adult: false,
      backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
      original_language: "en",
      original_title: "Inception",
      genre_ids: [28, 878, 12],
      title: "Origen",
      vote_average: 8.3,
      overview:
        "Dom Cobb es un ladrón hábil, el mejor de todos, especializado en el peligroso arte de extracción: el robo de secretos valiosos desde las profundidades del subconsciente durante el estado de sueño cuando la mente está más vulnerable. Esta habilidad excepcional de Cobb le ha hecho un jugador codiciado en el traicionero nuevo mundo de espionaje corporativo, pero al mismo tiempo, le ha convertido en un fugitivo internacional y ha tenido que sacrificar todo que le importaba. Ahora a Cobb se le ofrece una oportunidad para redimirse. Con un último trabajo podría recuperar su vida anterior, pero solamente si logra lo imposible.",
      release_date: "2010-07-15",
    },
    {
      popularity: 30.925,
      vote_count: 7180,
      video: false,
      poster_path: "/5VtVgiwgQ2DOIS1EtIPpvXLOOmG.jpg",
      id: 359940,
      adult: false,
      backdrop_path: "/bJLJAtGjBj836UjJZNOwgrfe5Ps.jpg",
      original_language: "en",
      original_title: "Three Billboards Outside Ebbing, Missouri",
      genre_ids: [80, 18],
      title: "Tres anuncios en las afueras",
      vote_average: 8.1,
      overview:
        "Mildred Hayes, una mujer de 50 años cuya hija adolescente ha sido violada y asesinada, decide iniciar por su cuenta una guerra contra la Policía de su pueblo, Ebbing, al considerar que no hacen lo suficiente para resolver el caso y que se haga justicia. Su primer paso será contratar unas vallas publicitarias denunciando la situación y señalando al jefe de policía, William Willoughby, como responsable principal de la pasividad policial.",
      release_date: "2017-11-10",
    },
    {
      popularity: 104.716,
      vote_count: 8827,
      video: false,
      poster_path: "/v5ZCVgxlFmlpFnR9DWVUkOVw4hW.jpg",
      id: 324786,
      adult: false,
      backdrop_path: "/6O0lsCK90jZCyPvyYSt8Szzlnd6.jpg",
      original_language: "en",
      original_title: "Hacksaw Ridge",
      genre_ids: [18, 36, 10752],
      title: "Hasta el último hombre",
      vote_average: 8.1,
      overview:
        "Narra la historia de Desmond Doss, un joven médico militar que participó en la sangrienta batalla de Okinawa, en el Pacífico durante la II Guerra Mundial, y se convirtió en el primer objetor de conciencia en la historia estadounidense en recibir la Medalla de Honor del Congreso. Doss quería servir a su país, pero desde pequeño se había hecho una promesa a sí mismo: no coger jamás ningún arma.",
      release_date: "2016-10-07",
    },
    {
      popularity: 27.653,
      id: 489,
      video: false,
      vote_count: 7915,
      vote_average: 8.1,
      title: "El indomable Will Hunting",
      release_date: "1997-12-05",
      original_language: "en",
      original_title: "Good Will Hunting",
      genre_ids: [18],
      backdrop_path: "/wuI6zBnLI5EuqdKEMBMQrhIbvOA.jpg",
      adult: false,
      overview:
        "Will es un joven rebelde con una inteligencia asombrosa, especialmente con las matemáticas. El descubrimiento de su talento por parte de los académicos le obligará a elegir entre seguir con su vida de siempre -un trabajo fácil, buenos amigos, muchas cervezas y alguna bronca- o aprovechar sus grandes cualidades intelectuales en alguna universidad. Sólo los consejos de un solitario y bohemio profesor le ayudará a decidirse.",
      poster_path: "/xefaYjW0dQfVbyEuazbC0LdtBh8.jpg",
    },
    {
      popularity: 48.015,
      id: 348,
      video: false,
      vote_count: 9679,
      vote_average: 8.1,
      title: "Alien, el octavo pasajero",
      release_date: "1979-05-25",
      original_language: "en",
      original_title: "Alien",
      genre_ids: [27, 878],
      backdrop_path: "/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg",
      adult: false,
      overview:
        "De regreso a la Tierra, la nave de carga Nostromo interrumpe su viaje y despierta a sus siete tripulantes. El ordenador central, MADRE, ha detectado la misteriosa transmisión de una forma de vida desconocida, procedente de un planeta cercano aparentemente deshabitado. La nave se dirige entonces al extraño planeta para investigar el origen de la comunicación.",
      poster_path: "/pZ9cAe5FxexJjpCaeiETbXzz3Fs.jpg",
    },
    {
      popularity: 13.978,
      id: 521,
      video: false,
      vote_count: 1577,
      vote_average: 8,
      title: "Crimen perfecto",
      release_date: "1954-05-29",
      original_language: "en",
      original_title: "Dial M for Murder",
      genre_ids: [80, 53],
      backdrop_path: "/jVMlfESb0TJ29w8CUDDofEprMmn.jpg",
      adult: false,
      overview:
        "Tony Wendice maquina un plan para deshacerse de Margot, su esposa infiel. Pero la casualidad hará que sea a ella a quien finalmente acusen de asesinato. La inestimable ayuda de un inspector de policía ayudará a resolver el misterioso crimen.",
      poster_path: "/wEdTSmjWddEmEeOIWWmXrRThvzY.jpg",
    },
    {
      popularity: 78.893,
      vote_count: 12162,
      video: false,
      poster_path: "/gk6IErM0acV6HJRwKZy8ecBoddc.jpg",
      id: 424694,
      adult: false,
      backdrop_path: "/93xA62uLd5CwMOAs37eQ7vPc1iV.jpg",
      original_language: "en",
      original_title: "Bohemian Rhapsody",
      genre_ids: [18, 10402],
      title: "Bohemian Rhapsody",
      vote_average: 8,
      overview:
        "Bohemian Rhapsody es una rotunda y sonora celebración de Queen, de su música y de su extraordinario cantante Freddie Mercury, que desafió estereotipos e hizo añicos tradiciones para convertirse en uno de los showmans más queridos del mundo. La película plasma el meteórico ascenso al olimpo de la música de la banda a través de sus icónicas canciones y su revolucionario sonido, su crisis cuando el estilo de vida de Mercury estuvo fuera de control, y su triunfal reunión en la víspera del Live Aid, en la que Mercury, mientras sufría una enfermedad que amenazaba su vida, lidera a la banda en uno de los conciertos de rock más grandes de la historia. Veremos cómo se cimentó el legado de una banda que siempre se pareció más a una familia, y que continúa inspirando a propios y extraños, soñadores y amantes de la música hasta nuestros días.",
      release_date: "2018-10-24",
    },
    {
      popularity: 37.158,
      id: 807,
      video: false,
      vote_count: 14014,
      vote_average: 8.3,
      title: "Seven",
      release_date: "1995-09-22",
      original_language: "en",
      original_title: "Se7en",
      genre_ids: [80, 9648, 53],
      backdrop_path: "/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg",
      adult: false,
      overview:
        "El teniente Somerset, del departamento de homicidios, está a punto de jubilarse y ser reemplazado por el ambicioso y brillante detective David Mills. Ambos tendrán que colaborar en la resolución de una serie de asesinatos cometidos por un psicópata que toma como base la relación de los siete pecados capitales: gula, pereza, soberbia, avaricia, envidia, lujuria e ira. Los cuerpos de las víctimas, sobre los que el asesino se ensaña de manera impúdica, se convertirán para los policías en un enigma que les obligará a viajar al horror y la barbarie más absoluta.",
      poster_path: "/uVPcVz4b2hnSGrXYLdIGRXwcivs.jpg",
    },
    {
      popularity: 57.898,
      id: 121,
      video: false,
      vote_count: 15514,
      vote_average: 8.3,
      title: "El señor de los anillos: las dos torres",
      release_date: "2002-12-18",
      original_language: "en",
      original_title: "The Lord of the Rings: The Two Towers",
      genre_ids: [12, 14, 28],
      backdrop_path: "/9BUvLUz1GhbNpcyQRyZm1HNqMq4.jpg",
      adult: false,
      overview:
        "La Compañía del Anillo se ha disuelto. El portador del anillo Frodo y su fiel amigo Sam se dirigen hacia Mordor para destruir el Anillo Único y acabar con el poder de Sauron. Mientras, y tras la dura batalla contra los orcos donde cayó Boromir, el hombre Aragorn, el elfo Legolas y el enano Gimli intentan rescatar a los medianos Merry y Pipin, secuestrados por los ogros de Mordor. Por su parte, Saurón y el traidor Sarumán continúan con sus planes en Mordor, en espera de la guerra contra las razas libres de la Tierra Media.",
      poster_path: "/qHEU9067PL8iIZULg7q58NvoWlS.jpg",
    },
    {
      popularity: 9.076,
      vote_count: 6668,
      video: false,
      poster_path: "/3sd6Q98cFSzoNzfIKZkMXiWHcpM.jpg",
      id: 641,
      adult: false,
      backdrop_path: "/c5g1Dn1tF22CS2oOvHDNKr1Ve2U.jpg",
      original_language: "en",
      original_title: "Requiem for a Dream",
      genre_ids: [80, 18, 53],
      title: "Réquiem por un sueño",
      vote_average: 8,
      overview:
        "Harry (Jared Leto) vive con su atormentada madre Sara (Ellen Burstyn), y mientras él sueña con una vida mejor, ella está permanentemente a dieta para el día que pueda cumplir su mayor ilusión; aparecer en su concurso televisivo preferido. La ambición de Harry y su novia Marion (Jennifer Connelly) es hacerse ricos vendiendo droga con su amigo Tyrone (Marlon Wayans), y utilizar las ganancias para abrir un negocio propio, pero nunca llega el dinero suficiente para iniciar su plan. A pesas de todo, Harry y Marion no se resignan a vivir una existencia que consideran despreciable, por lo que harán lo impensable para conseguir la vida que anhelan.",
      release_date: "2000-10-06",
    },
    {
      popularity: 34.955,
      vote_count: 13521,
      video: false,
      poster_path: "/fLXLNDsOBZxpNleWF9Z4hubxBUQ.jpg",
      id: 10681,
      adult: false,
      backdrop_path: "/ai2FicMUxLCurVkjtYdSvVDWRmS.jpg",
      original_language: "en",
      original_title: "WALL·E",
      genre_ids: [16, 10751, 878],
      title: "WALL·E",
      vote_average: 8,
      overview:
        "En el año 2700, en un planeta Tierra devastado y sin vida, tras cientos de solitarios años haciendo aquello para lo que fue construido -limpiar el planeta de basura- el pequeño robot WALL•E descubre una nueva misión en su vida cuando se encuentra con una moderna y lustrosa robot exploradora llamada EVE. Ambos viajarán a lo largo de la galaxia y vivirán una emocionante e inolvidable aventura.",
      release_date: "2008-06-22",
    },
    {
      popularity: 46.68,
      vote_count: 8643,
      video: false,
      poster_path: "/qtgdiEwBDdyyMj241DURRCiD5se.jpg",
      id: 280,
      adult: false,
      backdrop_path: "/xKb6mtdfI5Qsggc44Hr9CCUDvaj.jpg",
      original_language: "en",
      original_title: "Terminator 2: Judgment Day",
      genre_ids: [28, 53, 878],
      title: "Terminator 2: el juicio final",
      vote_average: 8,
      overview:
        "Ha pasado once años desde que Sarah Connor fue marcada como objetivo para ser eliminada por un cyborg del futuro. Ahora su hijo John, el futuro líder de la resistencia, es el objetivo de un Terminator más moderno, más mortífero. Una vez más, la resistencia se las ha ingeniado para enviar un protector de vuelta al pasado para intentar salvar a John y a su madre Sarah.",
      release_date: "1991-07-03",
    },
    {
      popularity: 34.726,
      vote_count: 4735,
      video: false,
      poster_path: "/rLPMD8BOHjvvjjCX7BZQdqNWBm2.jpg",
      id: 28178,
      adult: false,
      backdrop_path: "/gqxbhJT8THJX68ECwIhz4zyBUH5.jpg",
      original_language: "en",
      original_title: "Hachi: A Dog's Tale",
      genre_ids: [18, 10751],
      title: "Siempre a tu lado (Hachiko)",
      vote_average: 8,
      overview:
        "Basada en una historia real. Un profesor de universidad adopta a un perro vagabundo en una estación del tren. Tras recabar información sobre el animal, el profesor descubre que el perro iba a los andenes a diario durante semanas para esperar el regreso de su amo, pero éste había muerto en un accidente en la ciudad. El perro Hachiko, al lado de su nuevo amo a quien también le cambiará la vida cuando descubre los lazos que se pueden crear entre un animal y una persona.",
      release_date: "2009-06-13",
    },
    {
      popularity: 23.465,
      id: 76203,
      video: false,
      vote_count: 8371,
      vote_average: 8,
      title: "12 años de esclavitud",
      release_date: "2013-10-18",
      original_language: "en",
      original_title: "12 Years a Slave",
      genre_ids: [18, 36],
      backdrop_path: "/4Bb1kMIfrT2tYRZ9M6Jhqy6gkeF.jpg",
      adult: false,
      overview:
        "Basada en un hecho real ocurrido en 1850, narra la historia de Solomon Northup, un culto músico negro -y hombre libre- que vivía con su familia en Nueva York. Tras compartir una copa con dos desconocidos, Solomon descubre que ha sido drogado y secuestrado para ser vendido como esclavo en el Sur en una plantación de Louisiana. Renunciando a abandonar la esperanza, Solomon contempla cómo todos a su alrededor sucumben a la violencia, al abuso emocional y a la desesperanza. Entonces decide correr riesgos increíbles y confiar en la gente menos aparente para intentar recuperar su libertad y reunirse con su familia.",
      poster_path: "/1OoCd3fmjPHt9iCR4QxNGGrDyI0.jpg",
    },
    {
      popularity: 100.563,
      id: 157336,
      video: false,
      vote_count: 24124,
      vote_average: 8.3,
      title: "Interstellar",
      release_date: "2014-11-05",
      original_language: "en",
      original_title: "Interstellar",
      genre_ids: [12, 18, 878],
      backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
      adult: false,
      overview:
        "Narra las aventuras de un grupo de exploradores que hacen uso de un agujero de gusano recientemente descubierto para superar las limitaciones de los viajes espaciales tripulados y vencer las inmensas distancias que tiene un viaje interestelar.",
      poster_path: "/d1QKiYtceF3GDtxvTFXFAqwwah9.jpg",
    },
    {
      popularity: 226.564,
      vote_count: 15581,
      video: false,
      poster_path: "/br6krBFpaYmCSglLBWRuhui7tPc.jpg",
      id: 299534,
      adult: false,
      backdrop_path: "/orjiB3oUIsyz60hoEqkiGpy5CeO.jpg",
      original_language: "en",
      original_title: "Avengers: Endgame",
      genre_ids: [12, 878, 28],
      title: "Vengadores: Endgame",
      vote_average: 8.3,
      overview:
        "Después de los eventos devastadores de 'Vengadores: Infinity War', el universo está en ruinas debido a las acciones de Thanos. Con la ayuda de los aliados que quedaron, los Vengadores deberán reunirse una vez más para intentar deshacer sus acciones y restaurar el orden en el universo de una vez por todas, sin importar cuáles sean las consecuencias... Cuarta y última entrega de la saga \"Vengadores\".",
      release_date: "2019-04-24",
    },
    {
      popularity: 71.099,
      vote_count: 13121,
      video: false,
      poster_path: "/GdMDcacJra4ZmDaBIRASIpzjmU.jpg",
      id: 862,
      adult: false,
      backdrop_path: "/lxD5ak7BOoinRNehOCA85CQ8ubr.jpg",
      original_language: "en",
      original_title: "Toy Story",
      genre_ids: [16, 12, 10751, 35],
      title: "Toy Story",
      vote_average: 7.9,
      overview:
        "Los juguetes de Andy, un niño de seis años, temen que haya llegado su hora y que un nuevo regalo de cumpleaños les sustituya en el corazón de su dueño. Woody, un vaquero que ha sido hasta ahora el juguete favorito de Andy, trata de tranquilizarlos hasta que aparece Buzz Lightyear, un héroe espacial dotado de todo tipo de avances tecnológicos. Woody es relegado a un segundo plano., pero su constante rivalidad se transformará en una gran amistad cuando ambos se pierden en la ciudad sin saber cómo volver a casa.",
      release_date: "1995-10-30",
    },
    {
      popularity: 29.786,
      vote_count: 2382,
      video: false,
      poster_path: "/4hMcXuYwI4w42UNqAQsw4iNqSGu.jpg",
      id: 149,
      adult: false,
      backdrop_path: "/qZ4NYuwME0j6QgJmIE6AZMgmCaj.jpg",
      original_language: "ja",
      original_title: "アキラ",
      genre_ids: [16, 878, 28],
      title: "Akira",
      vote_average: 7.9,
      overview:
        "Corre el año 2019. Un estado policial, políticos tramposos, sectas religiosas, revolucionarios y un proyecto científico secreto se combinan para causar una atmósfera explosiva en Neo-Tokyo. Todos los grupos rivales quieren controlar a Akira, un chico con extraños poderes psíquicos que ha sido mantenido bajo custodia criogénica por más de 30 años. En medio de esta tensa atmósfera, un joven psíquico llamado Tetsuo libera a Akira.",
      release_date: "1988-07-16",
    },
    {
      popularity: 206.369,
      vote_count: 6880,
      video: false,
      poster_path: "/axdhbcZeOsfX3ZpwtgdgPIjc06l.jpg",
      id: 530915,
      adult: false,
      backdrop_path: "/cqa3sa4c4jevgnEJwq3CMF8UfTG.jpg",
      original_language: "en",
      original_title: "1917",
      genre_ids: [10752, 18],
      title: "1917",
      vote_average: 7.9,
      overview:
        "Nos encontramos en el año 1917. La Guerra Mundial amenazaba con cambiar, para siempre, el orden mundial. Ante la amenaza que se cernía, Estados Unidos decidió entrar en el conflicto con el objetivo de desequilibrar la balanza que caracterizaba a la contienda.",
      release_date: "2019-12-25",
    },
    {
      popularity: 32.085,
      id: 78,
      video: false,
      vote_count: 9676,
      vote_average: 7.9,
      title: "Blade Runner",
      release_date: "1982-06-25",
      original_language: "en",
      original_title: "Blade Runner",
      genre_ids: [878, 18, 53],
      backdrop_path: "/eIi3klFf7mp3oL5EEF4mLIDs26r.jpg",
      adult: false,
      overview:
        "A principios del siglo XXI, la Tyrell Corporation desarrolló un nuevo tipo de robot llamado Nexus, un ser virtualmente idéntico al hombre y conocido como Replicante.  Los Replicantes Nexus-6 eran superiores en fuerza y agilidad, y al menos iguales en inteligencia, a los ingenieros de genética que los crearon.  En el espacio exterior, los Replicantes fueron usados como trabajadores esclavos en la arriesgada exploración y colonización de otros planetas.  Después de la sangrienta rebelión de un equipo de combate de Nexus-6 en una colonia sideral, los Replicantes fueron declarados proscritos en la Tierra bajo pena de muerte.  Brigadas de policías especiales, con el nombre de Unidades de Blade Runners, tenían órdenes de tirar a matar al ver a cualquier Replicante invasor.  A esto no se le llamó ejecución, se le llamó retiro.",
      poster_path: "/k7tpmwwSqwJ6l1f1FqDMnM7x5c2.jpg",
    },
    {
      popularity: 243.548,
      id: 299536,
      video: false,
      vote_count: 20085,
      vote_average: 8.3,
      title: "Vengadores: Infinity War",
      release_date: "2018-04-25",
      original_language: "en",
      original_title: "Avengers: Infinity War",
      genre_ids: [12, 28, 878],
      backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
      adult: false,
      overview:
        "El todopoderoso Thanos ha despertado con la promesa de arrasar con todo a su paso, portando el Guantelete del Infinito, que le confiere un poder incalculable. Los únicos capaces de pararle los pies son los Vengadores y el resto de superhéroes de la galaxia, que deberán estar dispuestos a sacrificarlo todo por un bien mayor. Capitán América e Ironman deberán limar sus diferencias, Black Panther apoyará con sus tropas desde Wakanda, Thor y los Guardianes de la Galaxia e incluso Spider-Man se unirán antes de que los planes de devastación y ruina pongan fin al universo. ¿Serán capaces de frenar el avance del titán del caos?",
      poster_path: "/ksBQ4oHQDdJwND8H90ay8CbMihU.jpg",
    },
    {
      popularity: 54.491,
      vote_count: 14028,
      video: false,
      poster_path: "/drUbeOWuKYarYpD5E0lGnc6lfqf.jpg",
      id: 105,
      adult: false,
      backdrop_path: "/fq3wyOs1RHyz2yfzsb4sck7aWRG.jpg",
      original_language: "en",
      original_title: "Back to the Future",
      genre_ids: [12, 35, 878, 10751],
      title: "Regreso al futuro",
      vote_average: 8.3,
      overview:
        "Marty McFly es un adolescente amigo de Doc, un científico a los que todos menos él toman por chiflado. Cuando Doc crea una máquina para viajar en el tiempo en forma de un automóvil deportivo, Marty viaja accidentalmente al año 1955. Allí se encontrará con sus padres cuando eran jóvenes, pero impide su primer encuentro. A partir de entonces, y con el tiempo en su contra, McFly deberá conseguir que se enamoren para que se casen y él no deje de existir.",
      release_date: "1985-07-03",
    },
    {
      popularity: 63.574,
      vote_count: 11930,
      video: false,
      poster_path: "/p9hqo2JWhBytLxskz4FBKcP2e1k.jpg",
      id: 694,
      adult: false,
      backdrop_path: "/AdKA2F1SzYPhSZdEbjH1Zh75UVQ.jpg",
      original_language: "en",
      original_title: "The Shining",
      genre_ids: [27, 53],
      title: "El resplandor",
      vote_average: 8.2,
      overview:
        "Jack Torrance se traslada, junto a su mujer y a su hijo, al impresionante hotel Overlook, en Colorado, para encargarse del mantenimiento del mismo durante la temporada invernal, en la que permanece cerrado y aislado por la nieve. Su idea es escribir su novela al tiempo que cuida de las instalaciones durante esos largos y solitarios meses de invierno, pero desde su llegada al hotel, Jack comienza a padecer inquietantes transtornos de personalidad, al mismo tiempo que en el lugar comienzan a suceder diversos fenómenos paranormales.",
      release_date: "1980-05-23",
    },
    {
      popularity: 77.486,
      vote_count: 14529,
      video: false,
      poster_path: "/ahT4ObS7XKedQkOSpGr1wQ97aKA.jpg",
      id: 11,
      adult: false,
      backdrop_path: "/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg",
      original_language: "en",
      original_title: "Star Wars",
      genre_ids: [12, 28, 878],
      title: "La guerra de las galaxias. Episodio IV: Una nueva esperanza",
      vote_average: 8.2,
      overview:
        'La princesa Leia, líder del movimiento rebelde que desea reinstaurar la República en la galaxia en los tiempos ominosos del Imperio, es capturada por las malévolas Fuerzas Imperiales, capitaneadas por el implacable Darth Vader, el sirviente más fiel del emperador. El intrépido Luke Skywalker, ayudado por Han Solo, capitán de la nave espacial "El Halcón Milenario", y los androides, R2D2 y C3PO, serán los encargados de luchar contra el enemigo y rescatar a la princesa para volver a instaurar la justicia en el seno de la Galaxia.',
      release_date: "1977-05-25",
    },
    {
      popularity: 26.126,
      vote_count: 10776,
      video: false,
      poster_path: "/lIl2CrnWohGrZSO9eyKRptxZ7Hs.jpg",
      id: 1124,
      adult: false,
      backdrop_path: "/yCnJT53HMXAK87xzPAdjdYhZ3JE.jpg",
      original_language: "en",
      original_title: "The Prestige",
      genre_ids: [18, 9648, 53],
      title: "El truco final (El prestigio)",
      vote_average: 8.2,
      overview:
        "Robert Angier es un ilusionista respetado que se obsesiona con uno de los trucos de su rival Alfred Borden. Para conseguir el truco hará todo lo posible, sin saber hasta qué punto cambiará su vida...",
      release_date: "2006-10-19",
    },
    {
      popularity: 332.89,
      vote_count: 15437,
      video: false,
      poster_path: "/v0eQLbzT6sWelfApuYsEkYpzufl.jpg",
      id: 475557,
      adult: false,
      backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
      original_language: "en",
      original_title: "Joker",
      genre_ids: [80, 53, 18],
      title: "Joker",
      vote_average: 8.2,
      overview:
        "Arthur Fleck es un hombre ignorado por la sociedad, cuya motivación en la vida es hacer reír. Pero una serie de trágicos acontecimientos le llevarán a ver el mundo de otra forma. Película basada en Joker, el popular personaje de DC Comics y archivillano de Batman, pero que en este film toma un cariz más realista y oscuro.",
      release_date: "2019-10-02",
    },
    {
      popularity: 59.113,
      vote_count: 17998,
      video: false,
      poster_path: "/q4H9IreGqWgQcXq1JvvhcgfSN2w.jpg",
      id: 603,
      adult: false,
      backdrop_path: "/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
      original_language: "en",
      original_title: "The Matrix",
      genre_ids: [28, 878],
      title: "Matrix",
      vote_average: 8.1,
      overview:
        "Thomas Anderson lleva una doble vida: por el día es programador en una importante empresa de software, y por la noche un hacker informático llamado Neo. Su vida no volverá a ser igual cuando unos misteriosos personajes le inviten a descubrir la pregunta que no le deja dormir: ¿qué es Matrix?",
      release_date: "1999-03-30",
    },
  ],
};
module.exports = { moviesData };
